server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: LEGACYHTML5
    suffix: .html
    #页面默认路径
    prefix: classpath:/view/
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

  datasource:
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall,slf4j
    initialSize: 10
    minIdle: 10
    maxActive: 200
    maxWait: 60000
    removeAbandonedTimeout: 1800
    timeBetweenEvictionRunsMillis: 2000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 1
    removeAbandoned: true
    removeAbandTimeout: 1800
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  type-aliases-package: com.pbids.hit.model
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
# mapper
mapper:
  mappers:
    - com.sail.blog.base.BaseMapper
  not-empty: false
  identity: MYSQL


# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#日志显示
logging:
  level:
    com.sail.blog.mapper: DEBUG

# oss
oss:
  endpoint: http://oss-cn-shenzhen.aliyuncs.com
  accessKeyId: LTAI0kJYUTtnUSSh
  accessKeySecret: 4wwpDuSlasp3oAl8J9DVksrsQqIbZh
  url: http://travel-parent.oss-cn-shenzhen.aliyuncs.com/
  bucketName: travel-parent
