spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Hongkong&nullNamePatternMatchesAll=true
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  #redis
  redis:
    host: 120.79.150.120
    port: 6379
    password: hongbaoredis
    database: 10
    timeout: 5000
    pool:
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
